### ISSUE TITLE
could not find HalideConfig.cmake

### ISSUE THREAD

**Issue by liferlisiqi** [SuTanTank/Halide_OpenCV_Test#1]
hello
i have try your code, and meet following problem:

CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "FindHalide.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Halide", but
  CMake did not find one.

  Could not find a package configuration file provided by "Halide" with any
  of the following names:

    HalideConfig.cmake
    halide-config.cmake

  Add the installation prefix of "Halide" to CMAKE_PREFIX_PATH or set
  "Halide_DIR" to a directory containing one of the above files.  If "Halide"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

have you meet the same problem?

**Comment by SuTanTank** [comment]
用最新的halide

李思奇 <notifications@github.com> 于 2020年12月27日周日 11:17写道：

**Comment by liferlisiqi** [comment]
嗯， 是因为我没有make distrib
